<?php

declare(strict_types=1);

$projectRoot = __DIR__;
$requestPath = parse_url($_SERVER['REQUEST_URI'] ?? '/', PHP_URL_PATH) ?: '/';
$requestPath = rawurldecode($requestPath);

$routes = [
    '/' => '/php/index.php',
    '/index.php' => '/php/index.php',
    '/login.php' => '/php/login.php',
    '/register.php' => '/php/register.php',
    '/postular-tutor.php' => '/php/postular-tutor.php',
    '/logout.php' => '/php/logout.php',
    '/dashboard.php' => '/php/dashboard.php',
    '/notificaciones/' => '/php/notificaciones/index.php',
    '/notificaciones' => '/php/notificaciones/index.php',
    '/postulaciones-tutoria/' => '/php/postulaciones-tutoria/index.php',
    '/postulaciones-tutoria' => '/php/postulaciones-tutoria/index.php',
    '/postulaciones-tutoria/crear.php' => '/php/postulaciones-tutoria/crear.php',
    '/usuarios/' => '/usuarios/index.php',
    '/usuarios' => '/usuarios/index.php',
    '/usuarios/index.php' => '/usuarios/index.php',
    '/usuarios/create.php' => '/usuarios/create.php',
    '/usuarios/edit.php' => '/usuarios/edit.php',
    '/usuarios/delete.php' => '/usuarios/delete.php',
    '/usuarios/activate.php' => '/usuarios/activate.php',
    '/roles/' => '/php/roles/index.php',
    '/roles' => '/php/roles/index.php',
    '/roles/index.php' => '/php/roles/index.php',
    '/roles/create.php' => '/php/roles/create.php',
    '/roles/edit.php' => '/php/roles/edit.php',
    '/roles/delete.php' => '/php/roles/delete.php',
    '/carreras/' => '/php/carreras/index.php',
    '/carreras' => '/php/carreras/index.php',
    '/carreras/index.php' => '/php/carreras/index.php',
    '/carreras/create.php' => '/php/carreras/create.php',
    '/carreras/edit.php' => '/php/carreras/edit.php',
    '/carreras/delete.php' => '/php/carreras/delete.php',
    '/materias/' => '/php/materias/index.php',
    '/materias' => '/php/materias/index.php',
    '/materias/index.php' => '/php/materias/index.php',
    '/materias/create.php' => '/php/materias/create.php',
    '/materias/edit.php' => '/php/materias/edit.php',
    '/materias/delete.php' => '/php/materias/delete.php',
    '/tipos-tutoria/' => '/php/tipos-tutoria/index.php',
    '/tipos-tutoria' => '/php/tipos-tutoria/index.php',
    '/tipos-tutoria/index.php' => '/php/tipos-tutoria/index.php',
    '/tipos-tutoria/create.php' => '/php/tipos-tutoria/create.php',
    '/tipos-tutoria/edit.php' => '/php/tipos-tutoria/edit.php',
    '/tipos-tutoria/deactivate.php' => '/php/tipos-tutoria/deactivate.php',
    '/estudiantes/' => '/php/estudiantes/index.php',
    '/estudiantes' => '/php/estudiantes/index.php',
    '/estudiantes/index.php' => '/php/estudiantes/index.php',
    '/estudiantes/create.php' => '/php/estudiantes/create.php',
    '/estudiantes/edit.php' => '/php/estudiantes/edit.php',
    '/estudiantes/delete.php' => '/php/estudiantes/delete.php',
    '/tutores/' => '/php/tutores/index.php',
    '/tutores' => '/php/tutores/index.php',
    '/tutores/index.php' => '/php/tutores/index.php',
    '/tutores/create.php' => '/php/tutores/create.php',
    '/tutores/edit.php' => '/php/tutores/edit.php',
    '/tutores/delete.php' => '/php/tutores/delete.php',
    '/asignaciones/' => '/php/asignaciones/index.php',
    '/asignaciones' => '/php/asignaciones/index.php',
    '/asignaciones/index.php' => '/php/asignaciones/index.php',
    '/asignaciones/create.php' => '/php/asignaciones/create.php',
    '/asignaciones/delete.php' => '/php/asignaciones/delete.php',
    '/disponibilidad/' => '/php/disponibilidad/index.php',
    '/disponibilidad' => '/php/disponibilidad/index.php',
    '/disponibilidad/index.php' => '/php/disponibilidad/index.php',
    '/disponibilidad/create.php' => '/php/disponibilidad/create.php',
    '/disponibilidad/edit.php' => '/php/disponibilidad/edit.php',
    '/disponibilidad/delete.php' => '/php/disponibilidad/delete.php',
    '/tutorias/' => '/php/tutorias/index.php',
    '/tutorias' => '/php/tutorias/index.php',
    '/tutorias/index.php' => '/php/tutorias/index.php',
    '/tutorias/create.php' => '/php/tutorias/create.php',
    '/tutorias/programar.php' => '/php/tutorias/programar.php',
    '/tutorias/detalle.php' => '/php/tutorias/detalle.php',
    '/tutorias/status.php' => '/php/tutorias/status.php',
    '/evaluaciones/' => '/php/evaluaciones/index.php',
    '/evaluaciones' => '/php/evaluaciones/index.php',
    '/evaluaciones/index.php' => '/php/evaluaciones/index.php',
    '/evaluaciones/create.php' => '/php/evaluaciones/create.php',
    '/accesos/' => '/php/accesos/index.php',
    '/accesos' => '/php/accesos/index.php',
    '/accesos/index.php' => '/php/accesos/index.php',
    '/permisos/' => '/php/permisos/index.php',
    '/permisos' => '/php/permisos/index.php',
    '/permisos/index.php' => '/php/permisos/index.php',
    '/permisos/save_role.php' => '/php/permisos/save_role.php',
    '/periodos/' => '/php/periodos/index.php',
    '/periodos' => '/php/periodos/index.php',
    '/periodos/index.php' => '/php/periodos/index.php',
    '/periodos/create.php' => '/php/periodos/create.php',
    '/periodos/edit.php' => '/php/periodos/edit.php',
    '/periodos/delete.php' => '/php/periodos/delete.php',
    '/turnos/' => '/php/turnos/index.php',
    '/turnos' => '/php/turnos/index.php',
    '/turnos/index.php' => '/php/turnos/index.php',
    '/turnos/create.php' => '/php/turnos/create.php',
    '/turnos/edit.php' => '/php/turnos/edit.php',
    '/turnos/delete.php' => '/php/turnos/delete.php',
    '/aulas/' => '/php/aulas/index.php',
    '/aulas' => '/php/aulas/index.php',
    '/aulas/index.php' => '/php/aulas/index.php',
    '/aulas/create.php' => '/php/aulas/create.php',
    '/aulas/edit.php' => '/php/aulas/edit.php',
    '/ofertas/' => '/php/ofertas/index.php',
    '/ofertas' => '/php/ofertas/index.php',
    '/ofertas/index.php' => '/php/ofertas/index.php',
    '/ofertas/create.php' => '/php/ofertas/create.php',
    '/ofertas/edit.php' => '/php/ofertas/edit.php',
    '/ofertas/aulas-disponibles.php' => '/php/ofertas/aulas-disponibles.php',
    '/ofertas/open_group.php' => '/php/ofertas/open_group.php',
    '/ofertas/delete.php' => '/php/ofertas/delete.php',
    '/ofertas/revisar-baja-tutor.php' => '/php/ofertas/revisar-baja-tutor.php',
    '/solicitudes-tutor/' => '/php/solicitudes-tutor/index.php',
    '/solicitudes-tutor' => '/php/solicitudes-tutor/index.php',
    '/solicitudes-tutor/index.php' => '/php/solicitudes-tutor/index.php',
    '/solicitudes-tutor/revisar.php' => '/php/solicitudes-tutor/revisar.php',
    '/solicitudes/' => '/php/solicitudes/index.php',
    '/solicitudes' => '/php/solicitudes/index.php',
    '/solicitudes/index.php' => '/php/solicitudes/index.php',
    '/inscripciones/' => '/php/inscripciones/index.php',
    '/inscripciones' => '/php/inscripciones/index.php',
    '/inscripciones/index.php' => '/php/inscripciones/index.php',
    '/inscripciones/create.php' => '/php/inscripciones/create.php',
    '/inscripciones/cancel.php' => '/php/inscripciones/cancel.php',
    '/inscripciones/asignar-tutor.php' => '/php/inscripciones/asignar-tutor.php',
    '/modalidades-grado/' => '/php/mg/index.php',
    '/modalidades-grado' => '/php/mg/index.php',
    '/modalidades-grado/index.php' => '/php/mg/index.php',
    '/modalidades-grado/parametros.php' => '/php/mg/parametros.php',
    '/modalidades-grado/modalidades.php' => '/php/mg/modalidades.php',
    '/modalidades-grado/cohortes.php' => '/php/mg/cohortes.php',
    '/modalidades-grado/calendario.php' => '/php/mg/calendario.php',
    '/modalidades-grado/plantillas-calendario.php' => '/php/mg/plantillas-calendario.php',
    '/modalidades-grado/academico.php' => '/php/mg/academico.php',
    '/modalidades-grado/planes-estudiante.php' => '/php/mg/planes-estudiante.php',
    '/modalidades-grado/oferta-carreras.php' => '/php/mg/oferta-carreras.php',
    '/modalidades-grado/solicitudes.php' => '/php/mg/solicitudes.php',
    '/modalidades-grado/mi-solicitud.php' => '/php/mg/mi-solicitud.php',
    '/modalidades-grado/inscripciones.php' => '/php/mg/inscripciones.php',
    '/modalidades-grado/asignaciones-tutor.php' => '/php/mg/asignaciones-tutor.php',
    '/modalidades-grado/mis-trabajos.php' => '/php/mg/mis-trabajos.php',
    '/modalidades-grado/seguimiento.php' => '/php/mg/seguimiento.php',
    '/modalidades-grado/defensas.php' => '/php/mg/defensas.php',
    '/modalidades-grado/configuracion.php' => '/php/mg/configuracion.php',
    '/modalidades-grado/descargar-informe.php' => '/php/mg/descargar-informe.php',
    '/materias-disponibles/' => '/php/catalogo/materias.php',
    '/materias-disponibles' => '/php/catalogo/materias.php',
    '/tutores-disponibles/' => '/php/catalogo/tutores.php',
    '/tutores-disponibles' => '/php/catalogo/tutores.php',
    '/horarios-disponibles/' => '/php/catalogo/disponibilidad.php',
    '/horarios-disponibles' => '/php/catalogo/disponibilidad.php',
    '/mi-perfil-tutor/' => '/php/tutor/mi_perfil.php',
    '/mi-perfil-tutor' => '/php/tutor/mi_perfil.php',
    '/mi-perfil/' => '/php/perfil/index.php',
    '/mi-perfil' => '/php/perfil/index.php',
    '/mi-perfil/index.php' => '/php/perfil/index.php',
    '/mi-perfil/foto.php' => '/php/perfil/foto.php',
    '/mis-materias/' => '/php/tutor/mis_materias.php',
    '/mis-materias' => '/php/tutor/mis_materias.php',
    '/materias-ofertadas/' => '/php/tutor/mis_materias.php',
    '/materias-ofertadas' => '/php/tutor/mis_materias.php',
    '/materias-ofertadas/seleccionar.php' => '/php/tutor/mis_materias/aplicar.php',
    '/materias-ofertadas/horarios.php' => '/php/tutor/mis_materias/horarios.php',
    '/materias-ofertadas/cancelar.php' => '/php/tutor/mis_materias/cancelar.php',
    '/tutor/mis_materias/aplicar.php' => '/php/tutor/mis_materias/aplicar.php',
    '/tutor/mis_materias/horarios.php' => '/php/tutor/mis_materias/horarios.php',
];

if (isset($routes[$requestPath])) {
    require $projectRoot . $routes[$requestPath];
    return;
}

foreach (['css', 'js'] as $assetDirectory) {
    $assetRoot = realpath($projectRoot . DIRECTORY_SEPARATOR . $assetDirectory);
    $assetPath = realpath($projectRoot . DIRECTORY_SEPARATOR . ltrim($requestPath, '/'));

    if (
        $assetRoot !== false
        && $assetPath !== false
        && is_file($assetPath)
        && ($assetPath === $assetRoot || strpos($assetPath, $assetRoot . DIRECTORY_SEPARATOR) === 0)
    ) {
        return false;
    }
}

http_response_code(404);
echo 'Pagina no encontrada.';
