<?php require __DIR__ . '/../layouts/header.php'; ?>
<main class="container">
    <div class="page-heading"><div><h1>Materias disponibles</h1><p>Elige una materia y revisa sus tutores, horarios, aulas y cupos.</p></div><a class="button" href="<?= e(app_url('tutorias/')) ?>">Mis tutorias</a></div>
    <?php if ($message): ?><p class="success" role="status"><?= e($message) ?></p><?php endif; ?><?php if ($error): ?><p class="alert" role="alert"><?= e($error) ?></p><?php endif; ?>
    <?php foreach ($subjects as $offer): ?><?php $availableSeats = max(0, (int) $offer['cupo'] - (int) $offer['inscritos']); ?><section class="card offer-card" data-offer-card><div class="section-heading"><div><h2><?= e($offer['nombre_materia']) ?></h2><span class="table-profile-description"><?= e($offer['nombre_carrera'] ?: 'General') ?> | <?= e(ucfirst($offer['turno'])) ?> · Grupo <?= e($offer['nombre_grupo']) ?></span></div><div><span class="status status-<?= e($offer['estado']) ?>"><?= e($offer['estado']) ?></span><span class="table-profile-description"><?= $availableSeats ?> cupos disponibles de <?= (int) $offer['cupo'] ?></span></div></div><p class="form-hint"><strong><?= e($offer['nombre_periodo']) ?></strong>: <?= e($offer['fecha_inicio']) ?> a <?= e($offer['fecha_fin']) ?>. Inscripciones hasta <?= e($offer['inscripcion_fin']) ?>.</p><?php if ($offer['descripcion']): ?><p><?= e($offer['descripcion']) ?></p><?php endif; ?>
        <?php if ($offer['inscrito']): ?><p class="success">Ya tienes una inscripcion activa en esta oferta.</p><?php elseif ($availableSeats < 1): ?><p class="empty-state">La oferta no tiene cupos disponibles.</p><?php elseif ($offer['inscribibles']): ?><div class="table-wrapper"><table><thead><tr><th>Tutor</th><th>Perfil</th><th>Horario</th><th>Aula</th><th>Accion</th></tr></thead><tbody><?php foreach ($offer['inscribibles'] as $row): ?><tr><td><strong><?= e($row['tutor']) ?></strong></td><td><details><summary>Ver tutor</summary><span class="table-profile-description"><?= e($row['especialidad'] ?: 'Sin especialidad') ?></span><span class="table-profile-description"><?= e($row['biografia'] ?: 'Sin biografia') ?></span></details></td><td><?= e($row['dia_semana'] . ' ' . $row['nombre_turno']) ?><span class="table-profile-description"><?= e(substr($row['hora_inicio'], 0, 5) . ' - ' . substr($row['hora_fin'], 0, 5)) ?></span></td><td><?= e($row['nombre_aula'] ?: 'Sin aula') ?><?php if ($row['ubicacion']): ?><span class="table-profile-description"><?= e($row['ubicacion']) ?></span><?php endif; ?></td><td><form method="post" action="<?= e(app_url('inscripciones/create.php')) ?>"><input type="hidden" name="id_oferta" value="<?= (int) $offer['id_oferta'] ?>"><input type="hidden" name="id_oferta_tutor" value="<?= (int) $row['id_oferta_tutor'] ?>"><input type="hidden" name="id_oferta_horario" value="<?= (int) $row['id_oferta_horario'] ?>"><input type="hidden" name="csrf_token" value="<?= e(csrf_token()) ?>"><button class="btn btn-sm btn-primary" type="submit">Inscribirme</button></form></td></tr><?php endforeach; ?></tbody></table></div><?php else: ?><p class="empty-state">La oferta aun no tiene tutores confirmados con horarios disponibles.</p><?php endif; ?>
    </section><?php endforeach; ?>
    <?php if (!$subjects): ?><section class="card empty-state">No hay ofertas publicadas durante el periodo de inscripciones.</section><?php endif; ?>
</main>
<?php require __DIR__ . '/../layouts/footer.php'; ?>
