<?php require __DIR__ . '/../layouts/header.php'; ?>
<main class="container request-page">
    <div class="page-heading"><div><span class="hero-kicker">Tutorías académicas</span><h1><?= e($title) ?></h1><p><?= $role === 'administrador' ? 'Revisa postulaciones estudiantiles a ofertas publicadas. Aprobar crea la inscripción formal; el cupo se valida al decidir, no se reserva mientras está pendiente.' : 'Consulta el estado de tus postulaciones a ofertas de tutoría y las respuestas de Administración.' ?></p></div><?php if ($role === 'estudiante'): ?><a class="btn btn-outline-primary" href="<?= e(app_url('materias-disponibles/')) ?>">Ver ofertas</a><?php endif; ?></div>
    <?php if ($message): ?><p class="success" role="status"><?= e($message) ?></p><?php endif; ?>
    <?php if ($error): ?><p class="alert" role="alert"><?= e($error) ?></p><?php endif; ?>
    <?php if ($errors): ?><div class="alert" role="alert"><ul><?php foreach ($errors as $item): ?><li><?= e($item) ?></li><?php endforeach; ?></ul></div><?php endif; ?>

    <?php if ($role === 'administrador'): ?>
        <section class="card request-panel"><div class="section-heading"><div><h2>En espera de revisión</h2><p>Las postulaciones pendientes no ocupan cupo. Al aprobar, el sistema vuelve a verificar que la oferta siga abierta y tenga espacio.</p></div><span class="table-meta"><?= count($pending) ?> pendiente<?= count($pending) === 1 ? '' : 's' ?></span></div>
            <?php if ($pending): ?><div class="table-wrapper"><table><thead><tr><th>Estudiante / RU</th><th>Carrera</th><th>Oferta</th><th>Periodo / plazo</th><th>Cupo actual</th><th>Motivo</th><th>Decisión</th></tr></thead><tbody>
                <?php foreach ($pending as $application): $seatsLeft = max(0, (int) $application['cupo'] - (int) $application['inscritos']); $isOpen = $application['estado_oferta'] === 'publicada' && $application['fecha_fin'] >= date('Y-m-d') && $application['inscripcion_inicio'] <= date('Y-m-d') && $application['inscripcion_fin'] >= date('Y-m-d'); ?>
                    <tr><td><strong><?= e($application['estudiante']) ?></strong><span class="table-profile-description"><?= e($application['registro_universitario'] ?? 'Sin RU') ?></span><span class="table-profile-description"><?= e($application['correo']) ?></span></td><td><?= e($application['nombre_carrera']) ?></td><td><?= e($application['nombre_materia']) ?><span class="table-profile-description"><?= e($application['nombre_grupo'] . ' · ' . $application['tipo_tutoria'] . ' · ' . $application['turno']) ?></span></td><td><?= e($application['nombre_periodo']) ?><span class="table-profile-description">Postulación: <?= e($application['fecha_postulacion']) ?></span><span class="table-profile-description">Cierre: <?= e($application['inscripcion_fin']) ?></span></td><td><?= (int) $application['inscritos'] ?> / <?= (int) $application['cupo'] ?><span class="table-profile-description"><?= $seatsLeft ?> disponible<?= $seatsLeft === 1 ? '' : 's' ?> ahora</span></td><td><?= nl2br(e($application['motivo'] ?? '—')) ?></td><td>
                        <form class="request-review-form" method="post" action="<?= e(app_url('postulaciones-tutoria/')) ?>"><input type="hidden" name="csrf_token" value="<?= e(csrf_token()) ?>"><input type="hidden" name="id_postulacion" value="<?= (int) $application['id_postulacion'] ?>"><label class="sr-only" for="review-<?= (int) $application['id_postulacion'] ?>">Observación de revisión</label><input id="review-<?= (int) $application['id_postulacion'] ?>" class="form-control form-control-sm" name="observaciones_revision" maxlength="1000" placeholder="Motivo obligatorio si rechaza"><button class="btn btn-sm btn-primary" name="estado" value="aprobada" type="submit" <?= !$isOpen || $seatsLeft < 1 ? 'disabled title="Oferta cerrada o sin cupos; no se puede aprobar"' : '' ?>>Aprobar e inscribir</button><button class="btn btn-sm btn-outline-danger" name="estado" value="rechazada" type="submit">Rechazar</button></form>
                    </td></tr>
                <?php endforeach; ?>
            </tbody></table></div><?php else: ?><p class="empty-state">No hay postulaciones pendientes.</p><?php endif; ?>
        </section>
    <?php else: ?>
        <section class="card request-panel"><div class="section-heading"><div><h2>Historial de postulaciones</h2><p>Una postulación pendiente no reserva cupo. La inscripción solo se genera al aprobar.</p></div><span class="table-meta"><?= count($applications) ?> registro<?= count($applications) === 1 ? '' : 's' ?></span></div>
            <?php if ($applications): ?><div class="table-wrapper"><table><thead><tr><th>Oferta</th><th>Periodo / turno</th><th>Postulada</th><th>Estado</th><th>Resultado</th><th>Acción</th></tr></thead><tbody>
                <?php foreach ($applications as $application): ?><tr><td><?= e($application['nombre_materia']) ?><span class="table-profile-description">Grupo <?= e($application['nombre_grupo']) ?> · <?= e($application['tipo_tutoria']) ?></span></td><td><?= e($application['nombre_periodo']) ?><span class="table-profile-description"><?= e($application['turno']) ?> · <?= e($application['fecha_inicio']) ?></span></td><td><?= e($application['fecha_postulacion']) ?></td><td><span class="status status-<?= e($application['estado']) ?>"><?= e($application['estado']) ?></span></td><td><?php if ($application['estado'] === 'aprobada'): ?>Inscripción #<?= (int) $application['id_inscripcion'] ?> · <?= e($application['estado_inscripcion'] ?? 'inscrita') ?><?php elseif ($application['estado'] === 'rechazada'): ?><?= e($application['observaciones_revision'] ?? 'Sin comentario') ?><?php elseif ($application['estado'] === 'pendiente'): ?>En espera de revisión<?php else: ?><?= e($application['observaciones_revision'] ?? '—') ?><?php endif; ?></td><td><?php if ($application['estado'] === 'pendiente'): ?><form method="post" action="<?= e(app_url('postulaciones-tutoria/')) ?>"><input type="hidden" name="csrf_token" value="<?= e(csrf_token()) ?>"><input type="hidden" name="id_postulacion" value="<?= (int) $application['id_postulacion'] ?>"><button class="btn btn-sm btn-outline-danger" name="accion" value="cancelar" type="submit">Cancelar</button></form><?php else: ?>—<?php endif; ?></td></tr><?php endforeach; ?>
            </tbody></table></div><?php else: ?><p class="empty-state">Todavía no has postulado a una oferta.</p><?php endif; ?>
        </section>
    <?php endif; ?>
</main>
<?php require __DIR__ . '/../layouts/footer.php'; ?>
