<?php require __DIR__ . '/../layouts/header.php'; ?>
<main class="container mg-page">
    <div class="page-heading"><div><span class="hero-kicker">Cohortes MG</span><h1>Asignación de tutores</h1><p>Reasignar conserva el tutor anterior, fechas, responsable y observación.</p></div><a class="btn btn-outline-secondary" href="<?= e(app_url('modalidades-grado/cohortes.php')) ?>">Volver a Cohortes</a></div>
    <?php if ($message): ?><p class="success" role="status"><?= e($message) ?></p><?php endif; ?>
    <?php if ($errors): ?><div class="alert" role="alert"><ul><?php foreach ($errors as $error): ?><li><?= e($error) ?></li><?php endforeach; ?></ul></div><?php endif; ?>
    <?php if ($capacityRule['limite'] !== null): ?><p class="form-hint">Límite institucional confirmado: <?= (int) $capacityRule['limite'] ?> estudiantes activos por tutor.</p><?php else: ?><p class="alert">El límite de estudiantes por tutor está <?= e($capacityRule['estado_evidencia']) ?> y no bloqueará asignaciones. La carga actual se muestra como referencia.</p><?php endif; ?>
    <section class="card mg-panel"><h2>Trabajos activos</h2>
        <?php if ($works): ?><div class="table-wrapper"><table><thead><tr><th>Trabajo / modalidad</th><th>Cohorte</th><th>Estudiantes activos</th><th>Tutor actual</th><th>Carga global</th><th>Asignar / cambiar</th></tr></thead><tbody>
            <?php foreach ($works as $work): $workTutor = null; foreach ($tutors as $candidate) { if ((int) $candidate['id_tutor'] === (int) $work['id_tutor']) { $workTutor = $candidate; break; } } ?>
                <tr><td><?= e($work['codigo']) ?><br><small><?= e($work['modalidad']) ?> · <?= e($work['tipo_trabajo']) ?> · <?= e($work['tema'] ?? 'Sin tema') ?></small></td><td><?= e($work['codigo_cohorte'] . ' · ' . $work['cohorte']) ?></td><td><?= (int) $work['estudiantes_activos'] ?><?php if ($work['integrantes']): ?><br><small><?= e($work['integrantes']) ?></small><?php endif; ?></td>
                <td><?php if ((int) $work['requiere_tutor'] === 1): ?><?= e($work['tutor'] ?? 'Sin asignar') ?><?php else: ?><span class="form-hint">No requerido por modalidad</span><?php endif; ?></td>
                <td><?php if ($workTutor): ?><?= (int) $workTutor['estudiantes_activos'] ?><?php if ($capacityRule['limite'] !== null): ?> / <?= (int) $capacityRule['limite'] ?><?php else: ?> estudiantes<?php endif; ?><?php else: ?>—<?php endif; ?></td>
                <td><?php if ((int) $work['requiere_tutor'] === 1 && $tutors): ?><form class="mg-form-grid" method="post" action="<?= e(app_url('modalidades-grado/asignaciones-tutor.php')) ?>"><input type="hidden" name="csrf_token" value="<?= e(csrf_token()) ?>"><input type="hidden" name="id_trabajo" value="<?= (int) $work['id_trabajo'] ?>"><label>Tutor<select class="form-select" name="id_tutor" required><option value="">Seleccione tutor</option><?php foreach ($tutors as $tutor): $full = $capacityRule['limite'] !== null && (int) $tutor['estudiantes_activos'] + (int) $work['estudiantes_activos'] > (int) $capacityRule['limite']; ?><option value="<?= (int) $tutor['id_tutor'] ?>" <?= (int) $work['id_tutor'] === (int) $tutor['id_tutor'] ? 'selected' : '' ?> <?= $full && (int) $work['id_tutor'] !== (int) $tutor['id_tutor'] ? 'disabled' : '' ?>><?= e($tutor['apellido'] . ', ' . $tutor['nombre']) ?> · <?= (int) $tutor['estudiantes_activos'] ?><?= $capacityRule['limite'] !== null ? '/' . (int) $capacityRule['limite'] : ' est.' ?></option><?php endforeach; ?></select></label><label>Observación<input class="form-control" name="observacion" maxlength="1000"></label><button class="btn btn-sm btn-primary" type="submit"><?= $work['id_tutor'] ? 'Cambiar tutor' : 'Asignar tutor' ?></button></form><?php elseif ((int) $work['requiere_tutor'] === 1): ?><span class="form-hint">No hay tutores activos disponibles.</span><?php else: ?>—<?php endif; ?></td></tr>
            <?php endforeach; ?>
        </tbody></table></div><?php else: ?><p class="form-hint">Todavía no hay trabajos activos inscritos.</p><?php endif; ?>
    </section>
    <section class="card mg-panel"><h2>Tutores disponibles y carga actual</h2><?php if ($tutors): ?><div class="table-wrapper"><table><thead><tr><th>Tutor</th><th>Especialidad</th><th>Estudiantes activos</th><th>Límite</th></tr></thead><tbody><?php foreach ($tutors as $tutor): ?><tr><td><?= e($tutor['apellido'] . ', ' . $tutor['nombre']) ?></td><td><?= e($tutor['especialidad'] ?? '—') ?></td><td><?= (int) $tutor['estudiantes_activos'] ?></td><td><?= $capacityRule['limite'] === null ? 'No confirmado' : (int) $capacityRule['limite'] ?></td></tr><?php endforeach; ?></tbody></table></div><?php else: ?><p>No hay tutores activos disponibles.</p><?php endif; ?></section>
</main>
<?php require __DIR__ . '/../layouts/footer.php'; ?>
