<?php
require __DIR__ . '/../layouts/header.php';
$tribunalRule = $detail && (int) $detail['requiere_tribunal'] === 1;
$defenseRule = $detail && (int) $detail['requiere_defensa'] === 1;
$latestDefense = null;
foreach (($detail['defensas'] ?? []) as $defense) {
    if ($defense['estado'] !== 'cancelada') { $latestDefense = $defense; break; }
}
$attemptsUsed = $detail ? count(array_filter($detail['defensas'], static fn (array $defense): bool => $defense['estado'] !== 'cancelada')) : 0;
$maxReached = $detail && $detail['max_defensas'] !== null && $attemptsUsed >= (int) $detail['max_defensas'];
$observedAtLimit = $latestDefense && $latestDefense['estado'] === 'realizada'
    && $latestDefense['resultado'] === 'observado' && $maxReached;
$terminalDefense = $latestDefense && $latestDefense['estado'] === 'realizada'
    && (in_array($latestDefense['resultado'], ['aprobado', 'reprobado'], true) || $observedAtLimit);
$canClose = $detail && $detail['estado'] === 'activo' && $allReady && (!$defenseRule || $terminalDefense);
$tribunalPresident = null;
$tribunalMemberIds = [];
foreach (($detail['tribunal_miembros'] ?? []) as $member) {
    if ($member['rol'] === 'presidente') { $tribunalPresident = (int) $member['id_usuario']; }
    else { $tribunalMemberIds[] = (int) $member['id_usuario']; }
}
$maxDefenses = $detail ? $detail['max_defensas'] : null;
?>
<main class="container mg-page">
    <div class="page-heading"><div><span class="hero-kicker">Administración MG</span><h1>Defensas y cierre</h1><p>Revisa el checklist de cada trabajo, conforma tribunales, programa intentos y registra el cierre final.</p></div><a class="btn btn-outline-secondary" href="<?= e(app_url('modalidades-grado/')) ?>">Volver al resumen</a></div>
    <?php if ($message): ?><p class="success" role="status"><?= e($message) ?></p><?php endif; ?>
    <?php if ($errors): ?><div class="alert" role="alert"><ul><?php foreach ($errors as $error): ?><li><?= e($error) ?></li><?php endforeach; ?></ul></div><?php endif; ?>

    <section class="card mg-panel"><form class="mg-cohort-filter" method="get" action="<?= e(app_url('modalidades-grado/defensas.php')) ?>"><label>Trabajo<select class="form-select" name="id_trabajo" required><option value="">Seleccione</option><?php foreach ($works as $work): ?><option value="<?= (int) $work['id_trabajo'] ?>" <?= $detail && (int) $detail['id_trabajo'] === (int) $work['id_trabajo'] ? 'selected' : '' ?>><?= e($work['codigo'] . ' · ' . $work['modalidad'] . ' · ' . $work['codigo_cohorte']) ?><?= $work['estado_trabajo'] !== 'activo' ? ' · ' . e($work['estado_trabajo']) : '' ?></option><?php endforeach; ?></select></label><button class="btn btn-outline-primary" type="submit">Abrir</button></form>
        <?php if ($detail): ?><p class="mg-calendar-summary"><strong><?= e($detail['codigo'] . ' · ' . $detail['tema']) ?></strong><span><?= e($detail['modalidad']) ?></span><span><?= e($detail['codigo_cohorte'] . ' · ' . $detail['cohorte']) ?></span><span>Estado: <?= e($detail['estado']) ?></span></p><?php endif; ?>
    </section>

    <?php if ($detail): ?>
        <section class="card mg-panel"><h2>Checklist de habilitación</h2><?php if ($detail['checklist']): ?><div class="table-wrapper"><table><thead><tr><th>Requisito</th><th>Estado</th><th>Detalle</th></tr></thead><tbody><?php foreach ($detail['checklist'] as $item): ?><tr><td><?= e($item['nombre']) ?></td><td><span class="status <?= $item['ok'] ? 'status-activo' : 'status-inactivo' ?>"><?= $item['ok'] ? 'Cumple' : 'Pendiente' ?></span></td><td><?= e($item['detalle']) ?></td></tr><?php endforeach; ?></tbody></table></div><?php else: ?><p>No hay requisitos de checklist para este trabajo.</p><?php endif; ?>
            <?php if (!$defenseRule): ?><p class="form-hint">La modalidad no requiere defensa; el cierre administrativo puede definirse después de cumplir los requisitos configurados.</p><?php elseif ($maxDefenses === null): ?><p class="alert">La modalidad no tiene un máximo de defensas configurado; no se impondrá un límite automático.</p><?php endif; ?>
        </section>

        <section class="card mg-panel"><h2>Tribunal</h2><p>Al menos presidente y un miembro. Miembros se eligen de usuarios existentes con perfil de tutor/coordinación/auxiliar; no se crean personas duplicadas.</p>
            <?php if ($detail['tribunal_miembros']): ?><div class="table-wrapper"><table><thead><tr><th>Rol</th><th>Miembro</th><th>Perfil</th></tr></thead><tbody><?php foreach ($detail['tribunal_miembros'] as $member): ?><tr><td><?= e($member['rol']) ?></td><td><?= e($member['nombre'] . ' ' . $member['apellido']) ?></td><td><?= e($member['nombre_rol']) ?></td></tr><?php endforeach; ?></tbody></table></div><?php else: ?><p>No hay tribunal activo asignado.</p><?php endif; ?>
            <?php if ($detail['estado'] === 'activo'): ?><form class="mg-form-grid" method="post" action="<?= e(app_url('modalidades-grado/defensas.php?id_trabajo=' . (int) $detail['id_trabajo'])) ?>"><input type="hidden" name="csrf_token" value="<?= e(csrf_token()) ?>"><input type="hidden" name="id_trabajo" value="<?= (int) $detail['id_trabajo'] ?>"><input type="hidden" name="accion" value="tribunal"><label>Presidente<select class="form-select" name="presidente" required><option value="">Seleccione</option><?php foreach ($candidates as $candidate): ?><option value="<?= (int) $candidate['id_usuario'] ?>" <?= $tribunalPresident === (int) $candidate['id_usuario'] ? 'selected' : '' ?>><?= e($candidate['apellido'] . ', ' . $candidate['nombre'] . ' · ' . $candidate['nombre_rol']) ?></option><?php endforeach; ?></select></label><label>Miembros (selección múltiple)<select class="form-select" name="miembros[]" multiple size="5"><?php foreach ($candidates as $candidate): ?><option value="<?= (int) $candidate['id_usuario'] ?>" <?= in_array((int) $candidate['id_usuario'], $tribunalMemberIds, true) ? 'selected' : '' ?>><?= e($candidate['apellido'] . ', ' . $candidate['nombre'] . ' · ' . $candidate['nombre_rol']) ?></option><?php endforeach; ?></select></label><label>Observación<textarea class="form-control" name="observacion" rows="2" maxlength="1000"></textarea></label><button class="btn btn-outline-primary" type="submit"><?= $detail['tribunal_actual'] ? 'Reemplazar tribunal (conservar historial)' : 'Designar tribunal' ?></button></form><?php endif; ?>
            <?php if ($detail['tribunales']): ?><details><summary>Historial de tribunales</summary><ul><?php foreach ($detail['tribunales'] as $tribunal): ?><li>#<?= (int) $tribunal['id_tribunal'] ?> · <?= e($tribunal['estado']) ?> · <?= e($tribunal['designado_en']) ?><?= $tribunal['finalizado_en'] ? ' — reemplazado ' . e($tribunal['finalizado_en']) : '' ?></li><?php endforeach; ?></ul></details><?php endif; ?>
        </section>

        <?php if ($defenseRule): ?><section class="card mg-panel"><h2>Intentos de defensa</h2>
            <?php if ($detail['defensas']): ?><div class="table-wrapper"><table><thead><tr><th>Intento</th><th>Fecha y lugar</th><th>Estado</th><th>Resultado</th><th>Nota</th><th>Historial / acciones</th></tr></thead><tbody>
                <?php foreach ($detail['defensas'] as $defense): ?><tr><td>#<?= (int) $defense['numero_defensa'] ?></td><td><?= e($defense['fecha_hora']) ?><br><small><?= e($defense['ubicacion'] ?? '—') ?><br><?= e($defense['tribunal'] ?? 'Sin tribunal') ?></small></td><td><?= e($defense['estado']) ?></td><td><?= e($defense['resultado'] ?? '—') ?></td><td><?= e($defense['nota'] ?? '—') ?></td><td>
                    <?php if ($defense['estado'] === 'programada' && $detail['estado'] === 'activo'): ?><details><summary>Reprogramar / resultado</summary><form class="mg-form-grid" method="post" action="<?= e(app_url('modalidades-grado/defensas.php?id_trabajo=' . (int) $detail['id_trabajo'])) ?>"><input type="hidden" name="csrf_token" value="<?= e(csrf_token()) ?>"><input type="hidden" name="id_trabajo" value="<?= (int) $detail['id_trabajo'] ?>"><input type="hidden" name="id_defensa" value="<?= (int) $defense['id_defensa'] ?>"><input type="hidden" name="accion" value="reprogramar"><label>Nueva fecha/hora<input class="form-control" type="datetime-local" name="fecha_hora" required></label><label>Ubicación<input class="form-control" name="ubicacion" maxlength="255"></label><label>Motivo<input class="form-control" name="observaciones" maxlength="5000"></label><button class="btn btn-sm btn-outline-primary" type="submit">Reprogramar</button></form><form class="mg-form-grid" method="post" action="<?= e(app_url('modalidades-grado/defensas.php?id_trabajo=' . (int) $detail['id_trabajo'])) ?>"><input type="hidden" name="csrf_token" value="<?= e(csrf_token()) ?>"><input type="hidden" name="id_trabajo" value="<?= (int) $detail['id_trabajo'] ?>"><input type="hidden" name="id_defensa" value="<?= (int) $defense['id_defensa'] ?>"><input type="hidden" name="accion" value="resultado_defensa"><label>Resultado<select class="form-select" name="resultado"><option value="aprobado">Aprobado</option><option value="observado">Observado</option><option value="reprobado">Reprobado</option></select></label><label>Nota<input class="form-control" type="number" name="nota" min="0" max="100" step="0.01"></label><label>Observaciones<textarea class="form-control" name="observaciones" rows="2" maxlength="5000"></textarea></label><button class="btn btn-sm btn-primary" type="submit">Registrar resultado</button></form><form method="post" action="<?= e(app_url('modalidades-grado/defensas.php?id_trabajo=' . (int) $detail['id_trabajo'])) ?>"><input type="hidden" name="csrf_token" value="<?= e(csrf_token()) ?>"><input type="hidden" name="id_trabajo" value="<?= (int) $detail['id_trabajo'] ?>"><input type="hidden" name="id_defensa" value="<?= (int) $defense['id_defensa'] ?>"><input type="hidden" name="accion" value="cancelar_defensa"><label>Motivo cancelación<input class="form-control" name="observaciones" required maxlength="5000"></label><button class="btn btn-sm btn-outline-danger" type="submit">Cancelar intento</button></form></details><?php endif; ?>
                    <?php if ($defense['historial']): ?><details><summary>Historial del intento</summary><ul><?php foreach ($defense['historial'] as $event): ?><li><?= e($event['registrado_en']) ?> · <?= e($event['accion']) ?> · <?= e(($event['fecha_anterior'] ?? '—') . ' → ' . ($event['fecha_nueva'] ?? '—')) ?> · <?= e($event['actor']) ?><?= $event['observaciones'] ? ' — ' . e($event['observaciones']) : '' ?></li><?php endforeach; ?></ul></details><?php endif; ?>
                </td></tr><?php endforeach; ?>
            </tbody></table></div><?php else: ?><p>Aún no hay defensas programadas.</p><?php endif; ?>
            <?php $scheduled = (bool) array_filter($detail['defensas'], static fn(array $d): bool => $d['estado'] === 'programada'); ?>
            <?php if ($detail['estado'] === 'activo' && $allReady && !$scheduled && !$maxReached): ?><form class="mg-form-grid" method="post" action="<?= e(app_url('modalidades-grado/defensas.php?id_trabajo=' . (int) $detail['id_trabajo'])) ?>"><input type="hidden" name="csrf_token" value="<?= e(csrf_token()) ?>"><input type="hidden" name="id_trabajo" value="<?= (int) $detail['id_trabajo'] ?>"><input type="hidden" name="accion" value="programar_defensa"><label>Fecha y hora<input class="form-control" type="datetime-local" name="fecha_hora" required></label><label>Aula / ubicación<input class="form-control" name="ubicacion" maxlength="255"></label><label>Observación<input class="form-control" name="observaciones" maxlength="5000"></label><button class="btn btn-primary" type="submit">Programar defensa #<?= count($detail['defensas']) + 1 ?></button></form><?php elseif (!$allReady): ?><p class="alert">No se puede programar defensa hasta completar los elementos requeridos del checklist.</p><?php elseif ($maxReached && $observedAtLimit): ?><p class="alert">Se alcanzó el máximo de defensas observadas; el cierre solo puede registrarse como reprobado.</p><?php elseif ($maxReached): ?><p class="form-hint">Se alcanzó el máximo de defensas configurado.</p><?php endif; ?>
        </section><?php endif; ?>

        <?php if (!$detail['id_cierre'] && $detail['estado'] === 'activo'): ?><section class="card mg-panel"><h2>Cierre del proceso</h2><p>El cierre verifica requisitos de modalidad y resultado terminal de la última defensa; si se agotan intentos observados, el resultado de cierre es reprobado.</p><form class="mg-form-grid" method="post" action="<?= e(app_url('modalidades-grado/defensas.php?id_trabajo=' . (int) $detail['id_trabajo'])) ?>"><input type="hidden" name="csrf_token" value="<?= e(csrf_token()) ?>"><input type="hidden" name="id_trabajo" value="<?= (int) $detail['id_trabajo'] ?>"><input type="hidden" name="accion" value="cerrar"><label>Resultado final<select class="form-select" name="resultado"><option value="aprobado" <?= $terminalDefense && $latestDefense['resultado']==='aprobado'?'selected':'' ?>>Aprobado</option><option value="reprobado" <?= $observedAtLimit || ($terminalDefense && $latestDefense['resultado']==='reprobado')?'selected':'' ?>>Reprobado</option></select></label><label>Acta / observaciones<textarea class="form-control" name="observaciones" rows="3" maxlength="5000"></textarea></label><button class="btn btn-danger" type="submit" <?= !$canClose ? 'disabled' : '' ?>>Cerrar trabajo</button></form></section>
        <?php elseif ($detail['id_cierre']): ?><section class="card mg-panel"><h2>Proceso cerrado</h2><p>Resultado final: <strong><?= e($detail['resultado_cierre']) ?></strong> · <?= e($detail['cerrado_en']) ?> · <?= e($detail['cerrado_por_nombre']) ?></p><?php if ($detail['nota_cierre']): ?><p><?= nl2br(e($detail['nota_cierre'])) ?></p><?php endif; ?></section><?php endif; ?>
    <?php endif; ?>
</main>
<?php require __DIR__ . '/../layouts/footer.php'; ?>
