<?php require __DIR__ . '/../layouts/header.php';
$canManage = $role === 'administrador';
$attendance = $detail['asistencia'] ?? [];
$resultByStage = [];
foreach (($detail['resultados'] ?? []) as $result) { $resultByStage[$result['etapa']] = $result; }
?>
<main class="container mg-page">
    <div class="page-heading"><div><span class="hero-kicker"><?= $canManage ? 'Administración MG' : 'Tutor MG' ?></span><h1>Seguimiento del trabajo</h1><p>Informes versionados, sesiones, asistencia y resultados MDG I/II.</p></div></div>
    <?php if ($message): ?><p class="success" role="status"><?= e($message) ?></p><?php endif; ?>
    <?php if ($errors): ?><div class="alert" role="alert"><ul><?php foreach ($errors as $error): ?><li><?= e($error) ?></li><?php endforeach; ?></ul></div><?php endif; ?>

    <section class="card mg-panel"><form class="mg-cohort-filter" method="get" action="<?= e(app_url('modalidades-grado/seguimiento.php')) ?>"><label>Trabajo<select class="form-select" name="id_trabajo" required><?php foreach ($works as $option): ?><option value="<?= (int) $option['id_trabajo'] ?>" <?= $detail && (int) $detail['id_trabajo'] === (int) $option['id_trabajo'] ? 'selected' : '' ?>><?= e($option['codigo'] . ' · ' . $option['modalidad'] . ' · ' . $option['codigo_cohorte']) ?></option><?php endforeach; ?></select></label><button class="btn btn-outline-primary" type="submit">Ver seguimiento</button></form>
        <?php if ($detail): ?><div class="mg-calendar-summary"><strong><?= e($detail['codigo'] . ' · ' . $detail['tema']) ?></strong><span><?= e($detail['modalidad']) ?> · <?= e($detail['tipo_trabajo']) ?></span><span><?= e($detail['codigo_cohorte'] . ' · ' . $detail['cohorte']) ?></span><span><?= (int) $detail['estudiantes_activos'] ?> estudiante(s)</span></div>
            <div class="stat-grid"><article class="stat-card"><span class="stat-label">Hitos</span><strong class="stat-value"><?= count($detail['hitos']) ?></strong></article><article class="stat-card"><span class="stat-label">Hitos pendientes</span><strong class="stat-value"><?= count(array_filter($detail['hitos'],static fn(array $h):bool=>in_array($h['estado'],['pendiente','observado','corregido'],true))) ?></strong></article><article class="stat-card"><span class="stat-label">Sesiones</span><strong class="stat-value"><?= (int) $attendance['sesiones'] ?></strong></article><article class="stat-card"><span class="stat-label">Asistencia registrada</span><strong class="stat-value"><?= $attendance['porcentaje_presencia'] === null ? '—' : e(number_format((float) $attendance['porcentaje_presencia'],2)) . '%' ?></strong></article></div>
            <p class="form-hint">La asistencia es informativa en esta fase; no se aplica un mínimo como bloqueo.</p>
        <?php elseif (!$works): ?><p>Aún no tienes trabajos activos asignados.</p><?php endif; ?>
    </section>

    <?php if ($detail): ?>
        <section class="card mg-panel"><h2>Hitos e informes</h2>
            <?php if ($detail['hitos']): ?><div class="table-wrapper"><table><thead><tr><th>Orden / etapa</th><th>Hito</th><th>Fecha</th><th>Avance</th><th>Estado</th><th>Informes/versiones y revisión</th></tr></thead><tbody>
                <?php foreach ($detail['hitos'] as $milestone): ?><tr><td><?= (int) $milestone['orden'] ?> · <?= e(strtoupper($milestone['etapa'])) ?></td><td><?= e($milestone['nombre']) ?><br><small><?= e($milestone['tipo']) ?></small></td><td><?= e($milestone['fecha_limite'] ?? '—') ?><?= (int) $milestone['vencido'] === 1 ? ' · Vencido' : '' ?></td><td><?= $milestone['avance_real_pct'] === null ? '—' : e($milestone['avance_real_pct']) . '%' ?><?= $milestone['avance_esperado_pct'] === null ? '' : ' / esperado ' . e($milestone['avance_esperado_pct']) . '%' ?></td><td><?= e($milestone['estado']) ?></td><td>
                    <?php if ($milestone['versiones']): ?><ul><?php foreach ($milestone['versiones'] as $version): ?><li>V<?= (int) $version['numero_version'] ?> · <?= e($version['estado']) ?> · <a href="<?= e(app_url('modalidades-grado/descargar-informe.php?id=' . (int) $version['id_version'])) ?>">PDF: <?= e($version['nombre_archivo']) ?></a> · <?= e($version['subido_por']) ?> (<?= e($version['subido_en']) ?>)<?php if ($version['comentario_estudiante']): ?><br><small>Estudiante: <?= nl2br(e($version['comentario_estudiante'])) ?></small><?php endif; ?><?php if ($version['observacion_tutor']): ?><br><small>Revisión: <?= nl2br(e($version['observacion_tutor'])) ?></small><?php endif; ?>
                        <?php if ($canManage || $role === 'tutor'): ?><?php if ((int) $version['numero_version'] === (int) $milestone['version_actual'] && in_array($version['estado'], ['entregado','corregido'],true)): ?><form method="post" action="<?= e(app_url('modalidades-grado/seguimiento.php?id_trabajo=' . (int) $detail['id_trabajo'])) ?>"><input type="hidden" name="csrf_token" value="<?= e(csrf_token()) ?>"><input type="hidden" name="id_trabajo" value="<?= (int) $detail['id_trabajo'] ?>"><input type="hidden" name="id_version" value="<?= (int) $version['id_version'] ?>"><label>Comentario de revisión<textarea class="form-control" name="observacion_tutor" rows="2" maxlength="5000"></textarea></label><button class="btn btn-sm btn-outline-primary" name="accion" value="iniciar_revision">Iniciar revisión</button></form><?php elseif ((int) $version['numero_version'] === (int) $milestone['version_actual'] && $version['estado'] === 'en_revision'): ?><form class="mg-actions" method="post" action="<?= e(app_url('modalidades-grado/seguimiento.php?id_trabajo=' . (int) $detail['id_trabajo'])) ?>"><input type="hidden" name="csrf_token" value="<?= e(csrf_token()) ?>"><input type="hidden" name="id_trabajo" value="<?= (int) $detail['id_trabajo'] ?>"><input type="hidden" name="id_version" value="<?= (int) $version['id_version'] ?>"><input class="form-control" name="observacion_tutor" maxlength="5000" placeholder="Obligatoria al observar"><button class="btn btn-sm btn-outline-danger" name="accion" value="observar_informe">Observar</button><button class="btn btn-sm btn-primary" name="accion" value="aprobar_informe">Aprobar informe</button></form><?php endif; ?><?php endif; ?>
                    </li><?php endforeach; ?></ul><?php elseif ($milestone['tipo'] === 'informe' && (int) $milestone['requiere_informes'] === 1): ?><p>Sin informe cargado.</p><?php else: ?><p><?= e($milestone['observacion_estudiante'] ?? 'Sin entrega registrada.') ?></p><?php endif; ?>
                </td></tr><?php endforeach; ?>
            </tbody></table></div><?php else: ?><p>El trabajo no tiene hitos activos en su calendario.</p><?php endif; ?>
        </section>

        <?php if ($canManage || $role === 'tutor'): ?>
            <?php if ($sessionControlEnabled): ?><section class="card mg-panel"><h2>Programar sesión MG</h2><form class="mg-form-grid" method="post" action="<?= e(app_url('modalidades-grado/seguimiento.php?id_trabajo=' . (int) $detail['id_trabajo'])) ?>"><input type="hidden" name="csrf_token" value="<?= e(csrf_token()) ?>"><input type="hidden" name="id_trabajo" value="<?= (int) $detail['id_trabajo'] ?>"><input type="hidden" name="accion" value="crear_sesion"><label>Tipo<select class="form-select" name="tipo"><option value="seguimiento">Seguimiento</option><option value="tutoria">Tutoría MG</option><option value="taller">Taller</option></select></label><label>Título<input class="form-control" name="titulo" maxlength="180" required></label><label>Fecha/hora inicio<input class="form-control" type="datetime-local" name="inicio" required></label><label>Fecha/hora fin<input class="form-control" type="datetime-local" name="fin"></label><label>Modalidad<select class="form-select" name="modalidad"><option value="presencial">Presencial</option><option value="virtual">Virtual</option></select></label><label>Ubicación/enlace<input class="form-control" name="ubicacion" maxlength="255"></label><label>Hito relacionado<select class="form-select" name="id_seguimiento"><option value="">Sin hito</option><?php foreach ($detail['hitos'] as $milestone): ?><option value="<?= (int) $milestone['id_seguimiento'] ?>"><?= e($milestone['orden'] . '. ' . $milestone['nombre']) ?></option><?php endforeach; ?></select></label><label>Descripción<textarea class="form-control" name="descripcion" rows="2" maxlength="5000"></textarea></label><button class="btn btn-primary" type="submit">Programar sesión</button></form></section><?php else: ?><p class="form-hint">El control de tutorías MG está desactivado; las sesiones históricas siguen visibles.</p><?php endif; ?>
        <?php endif; ?>

        <section class="card mg-panel"><h2>Sesiones y asistencia</h2>
            <?php if ($detail['sesiones']): ?><?php foreach ($detail['sesiones'] as $session): ?><article class="mg-panel"><h3><?= e($session['titulo']) ?> · <?= e($session['tipo']) ?></h3><p><?= e($session['inicio']) ?><?= $session['fin'] ? ' – ' . e($session['fin']) : '' ?> · <?= e($session['modalidad']) ?> · <?= e($session['ubicacion'] ?? 'Sin ubicación') ?> · <?= e($session['estado']) ?><?= $session['tutor'] ? ' · Tutor: ' . e($session['tutor']) : '' ?></p><?php if ($session['descripcion']): ?><p><?= nl2br(e($session['descripcion'])) ?></p><?php endif; ?>
                    <?php if ($canManage || $role === 'tutor'): ?><form method="post" action="<?= e(app_url('modalidades-grado/seguimiento.php?id_trabajo=' . (int) $detail['id_trabajo'])) ?>"><input type="hidden" name="csrf_token" value="<?= e(csrf_token()) ?>"><input type="hidden" name="id_trabajo" value="<?= (int) $detail['id_trabajo'] ?>"><input type="hidden" name="id_sesion" value="<?= (int) $session['id_sesion'] ?>"><table><thead><tr><th>Estudiante</th><th>Estado de asistencia</th><th>Observación</th></tr></thead><tbody><?php foreach ($session['asistentes'] as $attendee): ?><tr><td><?= e($attendee['estudiante']) ?> (<?= e($attendee['registro_universitario'] ?? '—') ?>)</td><td><select class="form-select" name="asistencia[<?= (int) $attendee['id_estudiante'] ?>]"><?php foreach (['pendiente'=>'Pendiente','presente'=>'Presente','ausente'=>'Ausente','justificada'=>'Justificada'] as $key=>$label): ?><option value="<?= e($key) ?>" <?= $attendee['estado']===$key?'selected':'' ?>><?= e($label) ?></option><?php endforeach; ?></select></td><td><input class="form-control" name="observacion_asistencia[<?= (int) $attendee['id_estudiante'] ?>]" maxlength="500" value="<?= e($attendee['observacion'] ?? '') ?>"></td></tr><?php endforeach; ?></tbody></table><button class="btn btn-sm btn-primary" name="accion" value="guardar_asistencia">Guardar asistencia</button></form><?php else: ?><p>Asistencia registrada: <?= (int) $session['presentes'] ?> presente(s), <?= (int) $session['ausentes'] ?> ausente(s), <?= (int) $session['justificadas'] ?> justificada(s), <?= (int) $session['sin_registrar'] ?> pendiente(s).</p><?php endif; ?>
                </article><?php endforeach; ?><?php else: ?><p>No hay sesiones registradas.</p><?php endif; ?>
        </section>

        <section class="card mg-panel"><h2>MDG I y MDG II</h2><p>Los resultados son independientes del módulo general de Evaluaciones. Nota y porcentaje no aplican reglas automáticas de aprobación.</p>
            <?php foreach (['mdg1'=>'MDG I','mdg2'=>'MDG II'] as $stage=>$label): $result=$resultByStage[$stage]??null; ?><article class="mg-panel"><h3><?= e($label) ?> · <?= e($result['estado'] ?? 'pendiente') ?><?= $result && $result['nota']!==null ? ' · Nota ' . e($result['nota']) : '' ?></h3><?php if ($result && $result['observaciones']): ?><p><?= nl2br(e($result['observaciones'])) ?></p><?php endif; ?>
                <?php if ($result && $result['historial']): ?><details><summary>Historial de resultados</summary><ul><?php foreach ($result['historial'] as $event): ?><li><?= e($event['registrado_en']) ?> · <?= e(($event['estado_anterior']??'—').' → '.$event['estado_nuevo']) ?><?= $event['nota']===null?'':' · '.e($event['nota']) ?> · <?= e($event['registrado_por']) ?><?= $event['observaciones']?' — '.e($event['observaciones']):'' ?></li><?php endforeach; ?></ul></details><?php endif; ?>
                <?php if ($canManage || $role==='tutor'): ?><form class="mg-form-grid" method="post" action="<?= e(app_url('modalidades-grado/seguimiento.php?id_trabajo='.(int)$detail['id_trabajo'])) ?>"><input type="hidden" name="csrf_token" value="<?= e(csrf_token()) ?>"><input type="hidden" name="id_trabajo" value="<?= (int)$detail['id_trabajo'] ?>"><input type="hidden" name="etapa" value="<?= e($stage) ?>"><label>Estado<select class="form-select" name="estado"><?php foreach (['pendiente','en_curso','observado','aprobado','reprobado'] as $state): ?><option value="<?= e($state) ?>" <?= ($result['estado']??'pendiente')===$state?'selected':'' ?>><?= e($state) ?></option><?php endforeach; ?></select></label><label>Nota<input class="form-control" type="number" min="0" max="100" step="0.01" name="nota" value="<?= e($result['nota']??'') ?>"></label><label>Observaciones<textarea class="form-control" name="observaciones" rows="2" maxlength="5000"></textarea></label><button class="btn btn-outline-primary" name="accion" value="guardar_etapa">Guardar <?= e($label) ?></button></form><?php endif; ?>
            </article><?php endforeach; ?>
        </section>
    <?php endif; ?>
</main>
<?php require __DIR__ . '/../layouts/footer.php'; ?>
