<?php require __DIR__ . '/../layouts/header.php'; ?>
<main class="container mg-page">
    <div class="page-heading"><div><span class="hero-kicker">Administración MG</span><h1>Solicitudes de Modalidad de Grado</h1><p>La aprobación y la habilitación son decisiones separadas. Esta fase no crea la inscripción formal.</p></div><a class="btn btn-outline-secondary" href="<?= e(app_url('modalidades-grado/')) ?>">Volver al resumen</a></div>
    <?php if ($message): ?><p class="success" role="status"><?= e($message) ?></p><?php endif; ?>
    <?php if ($errors): ?><div class="alert" role="alert"><ul><?php foreach ($errors as $error): ?><li><?= e($error) ?></li><?php endforeach; ?></ul></div><?php endif; ?>
    <section class="card mg-panel">
        <form class="mg-cohort-filter" method="get" action="<?= e(app_url('modalidades-grado/solicitudes.php')) ?>">
            <label>Estado<select class="form-select" name="estado"><option value="">Todas</option><?php foreach (['enviada', 'en_revision', 'observada', 'aprobada', 'rechazada', 'cancelada', 'borrador'] as $option): ?><option value="<?= e($option) ?>" <?= $state === $option ? 'selected' : '' ?>><?= e($option) ?></option><?php endforeach; ?></select></label><button class="btn btn-outline-primary">Filtrar</button>
        </form>
        <?php if ($requests): ?><div class="table-wrapper"><table><thead><tr><th>Solicitud</th><th>Estudiante / RU</th><th>Carrera</th><th>Modalidad</th><th>Enviada</th><th>Estado</th><th>Habilitación</th><th>Detalle</th></tr></thead><tbody>
            <?php foreach ($requests as $request): ?><tr><td>#<?= (int) $request['id_solicitud'] ?></td><td><?= e($request['estudiante']) ?><br><small><?= e($request['registro_universitario'] ?? 'Sin RU') ?></small></td><td><?= e($request['nombre_carrera']) ?></td><td><?= e($request['modalidad']) ?></td><td><?= e($request['enviado_en'] ?? '—') ?></td><td><?= e($request['estado']) ?></td><td><?= $request['habilitado_en'] ? e($request['habilitado_en']) : '—' ?></td><td><a class="btn btn-sm btn-outline-primary" href="<?= e(app_url('modalidades-grado/solicitudes.php?id=' . (int) $request['id_solicitud'] . '&estado=' . rawurlencode($state))) ?>">Revisar</a></td></tr><?php endforeach; ?>
        </tbody></table></div><?php else: ?><p class="form-hint">No hay solicitudes para este filtro.</p><?php endif; ?>
    </section>

    <?php if ($selectedRequest): $currentAcademic = $selectedRequest['verificacion_actual']; $currentAcademicComplete = $currentAcademic && (int) $currentAcademic['materias_requeridas'] > 0 && (int) $currentAcademic['materias_aprobadas'] === (int) $currentAcademic['materias_requeridas']; ?>
        <section class="card mg-panel">
            <h2>Solicitud #<?= (int) $selectedRequest['id_solicitud'] ?> · <?= e($selectedRequest['estado']) ?></h2>
            <div class="stat-grid"><article class="stat-card"><span class="stat-label">Estudiante / RU</span><strong><?= e($selectedRequest['estudiante']) ?><br><?= e($selectedRequest['registro_universitario'] ?? '—') ?></strong></article><article class="stat-card"><span class="stat-label">Carrera</span><strong><?= e($selectedRequest['nombre_carrera']) ?></strong></article><article class="stat-card"><span class="stat-label">Modalidad</span><strong><?= e($selectedRequest['modalidad']) ?></strong></article><article class="stat-card"><span class="stat-label">Cuenta</span><strong><?= e($selectedRequest['estado_usuario']) ?></strong></article></div>
            <p><strong>Tipo de trabajo:</strong> <?= e($selectedRequest['tipo_trabajo']) ?> · <strong>Enviada:</strong> <?= e($selectedRequest['enviado_en'] ?? '—') ?></p>
            <?php if ($selectedRequest['tema_preliminar']): ?><p><strong>Tema preliminar:</strong> <?= e($selectedRequest['tema_preliminar']) ?></p><?php endif; ?>
            <?php if ($selectedRequest['descripcion']): ?><p><strong>Descripción:</strong><br><?= nl2br(e($selectedRequest['descripcion'])) ?></p><?php endif; ?>
            <?php if ($selectedRequest['observaciones_estudiante']): ?><p><strong>Nota del estudiante:</strong><br><?= nl2br(e($selectedRequest['observaciones_estudiante'])) ?></p><?php endif; ?>
            <h3>Verificación registrada al envío</h3>
            <p>Plan #<?= e($selectedRequest['id_plan_verificado'] ?? '—') ?> · Materias aprobadas: <?= e($selectedRequest['materias_aprobadas_snapshot'] ?? '—') ?> / <?= e($selectedRequest['materias_requeridas_snapshot'] ?? '—') ?> · Promedio informativo: <?= $selectedRequest['promedio_snapshot'] === null ? '—' : e(number_format((float) $selectedRequest['promedio_snapshot'], 2)) ?> · Verificado: <?= e($selectedRequest['verificado_en'] ?? '—') ?></p>
            <h3>Estado académico actual</h3>
            <?php if ($currentAcademic): ?><p>Plan <?= e($currentAcademic['codigo_plan'] . ' / ' . $currentAcademic['version_plan']) ?> · Aprobadas <?= (int) $currentAcademic['materias_aprobadas'] ?> / <?= (int) $currentAcademic['materias_requeridas'] ?> · Promedio <?= $currentAcademic['promedio_aprobadas'] === null ? '—' : e(number_format((float) $currentAcademic['promedio_aprobadas'], 2)) ?></p>
                <?php if ($selectedRequest['materias_pendientes_actuales']): ?><ul><?php foreach ($selectedRequest['materias_pendientes_actuales'] as $subject): ?><li><?= e($subject['nombre_materia']) ?> — <?= $subject['registrada'] ? 'sin aprobación' : 'sin registro' ?></li><?php endforeach; ?></ul><?php endif; ?>
            <?php else: ?><p class="alert">No existe un plan asignado con historial aprobado que permita verificar actualmente.</p><?php endif; ?>
            <p><strong>Modalidad aún disponible:</strong> <?= (int) $selectedRequest['modalidad_disponible'] === 1 ? 'Sí' : 'No' ?></p>
        </section>

        <?php if ($selectedRequest['estado'] === 'enviada'): ?>
            <section class="card mg-panel"><h3>Iniciar revisión</h3><form method="post" action="<?= e(app_url('modalidades-grado/solicitudes.php?id=' . $requestId . '&estado=' . rawurlencode($state))) ?>"><input type="hidden" name="csrf_token" value="<?= e(csrf_token()) ?>"><input type="hidden" name="id_solicitud" value="<?= $requestId ?>"><label>Nota interna (opcional)<textarea class="form-control" name="observacion" rows="2" maxlength="5000"></textarea></label><button class="btn btn-primary" name="accion" value="iniciar_revision">Iniciar revisión</button></form></section>
        <?php elseif ($selectedRequest['estado'] === 'en_revision'): ?>
            <section class="card mg-panel"><h3>Decisión administrativa</h3><form class="mg-form-grid" method="post" action="<?= e(app_url('modalidades-grado/solicitudes.php?id=' . $requestId . '&estado=' . rawurlencode($state))) ?>"><input type="hidden" name="csrf_token" value="<?= e(csrf_token()) ?>"><input type="hidden" name="id_solicitud" value="<?= $requestId ?>"><label>Observación / motivo (obligatorio al observar o rechazar)<textarea class="form-control" name="observacion" rows="3" maxlength="5000"></textarea></label><div class="mg-actions"><button class="btn btn-outline-primary" name="accion" value="observar">Observar</button><button class="btn btn-outline-danger" name="accion" value="rechazar">Rechazar</button><button class="btn btn-primary" name="accion" value="aprobar" <?= !$currentAcademicComplete || (int) $selectedRequest['modalidad_disponible'] !== 1 || $selectedRequest['estado_usuario'] !== 'activo' ? 'disabled' : '' ?>>Aprobar solicitud</button></div></form></section>
        <?php elseif ($selectedRequest['estado'] === 'aprobada' && !$selectedRequest['id_habilitacion']): ?>
            <section class="card mg-panel"><h3>Habilitación formal</h3><p>La habilitación se registra aparte; no crea una inscripción formal.</p><form method="post" action="<?= e(app_url('modalidades-grado/solicitudes.php?id=' . $requestId . '&estado=' . rawurlencode($state))) ?>"><input type="hidden" name="csrf_token" value="<?= e(csrf_token()) ?>"><input type="hidden" name="id_solicitud" value="<?= $requestId ?>"><label>Observación (opcional)<textarea class="form-control" name="observacion" rows="2" maxlength="1000"></textarea></label><button class="btn btn-primary" name="accion" value="habilitar" <?= !$currentAcademicComplete || (int) $selectedRequest['modalidad_disponible'] !== 1 || $selectedRequest['estado_usuario'] !== 'activo' ? 'disabled' : '' ?>>Habilitar proceso</button></form></section>
        <?php elseif ($selectedRequest['id_habilitacion']): ?><section class="card mg-panel"><h3>Habilitación registrada</h3><p><?= e($selectedRequest['habilitado_en']) ?> por <?= e($selectedRequest['habilitado_por'] ?? 'Administración') ?><?= $selectedRequest['observacion_habilitacion'] ? ' — ' . e($selectedRequest['observacion_habilitacion']) : '' ?></p></section><?php endif; ?>

        <section class="card mg-panel"><h3>Historial de auditoría</h3><?php if ($selectedRequest['historial']): ?><div class="table-wrapper"><table><thead><tr><th>Fecha</th><th>Acción</th><th>Estado</th><th>Responsable</th><th>Comentario</th><th>Visibilidad</th><th>Resumen académico</th></tr></thead><tbody><?php foreach ($selectedRequest['historial'] as $event): ?><tr><td><?= e($event['ocurrido_en']) ?></td><td><?= e($event['accion']) ?></td><td><?= e(($event['estado_anterior'] ?? '—') . ' → ' . $event['estado_nuevo']) ?></td><td><?= e($event['actor']) ?></td><td><?= nl2br(e($event['comentario'] ?? '—')) ?></td><td><?= (int) $event['visible_estudiante'] === 1 ? 'Visible al estudiante' : 'Interno' ?></td><td><code><?= e($event['resumen_academico'] ?? '—') ?></code></td></tr><?php endforeach; ?></tbody></table></div><?php else: ?><p>Sin eventos.</p><?php endif; ?></section>
    <?php endif; ?>
</main>
<?php require __DIR__ . '/../layouts/footer.php'; ?>
