<?php require __DIR__ . '/../layouts/header.php'; ?>
<main class="container mg-page">
    <div class="page-heading"><div><span class="hero-kicker">Administración MG</span><h1>Solicitudes de Modalidad de Grado</h1><p>La aprobación y la habilitación son decisiones separadas. Esta fase no crea la inscripción formal.</p></div><a class="btn btn-outline-secondary" href="<?= e(app_url('modalidades-grado/')) ?>">Volver al resumen</a></div>
    <?php if ($message): ?><p class="success" role="status"><?= e($message) ?></p><?php endif; ?>
    <?php if ($errors): ?><div class="alert" role="alert"><ul><?php foreach ($errors as $error): ?><li><?= e($error) ?></li><?php endforeach; ?></ul></div><?php endif; ?>
    <section class="card mg-panel">
        <form class="mg-cohort-filter" method="get" action="<?= e(app_url('modalidades-grado/solicitudes.php')) ?>">
            <label>Estado<select class="form-select" name="estado"><option value="">Todas</option><?php foreach (['enviada', 'en_revision', 'observada', 'aprobada', 'rechazada', 'cancelada', 'borrador'] as $option): ?><option value="<?= e($option) ?>" <?= $state === $option ? 'selected' : '' ?>><?= e($option) ?></option><?php endforeach; ?></select></label><button class="btn btn-outline-primary">Filtrar</button>
        </form>
        <?php if ($requests): ?><div class="table-wrapper"><table><thead><tr><th>Solicitud</th><th>Estudiante / RU</th><th>Carrera</th><th>Modalidad</th><th>Enviada</th><th>Estado</th><th>Habilitación</th><th>Detalle</th></tr></thead><tbody>
            <?php foreach ($requests as $request): ?><tr><td>#<?= (int) $request['id_solicitud'] ?></td><td><?= e($request['estudiante']) ?><br><small><?= e($request['registro_universitario'] ?? 'Sin RU') ?></small></td><td><?= e($request['nombre_carrera']) ?></td><td><?= e($request['modalidad']) ?></td><td><?= e($request['enviado_en'] ?? '—') ?></td><td><?= e($request['estado']) ?></td><td><?= $request['habilitado_en'] ? e($request['habilitado_en']) : '—' ?></td><td><a class="btn btn-sm btn-outline-primary" href="<?= e(app_url('modalidades-grado/solicitudes.php?id=' . (int) $request['id_solicitud'] . '&estado=' . rawurlencode($state))) ?>">Revisar</a></td></tr><?php endforeach; ?>
        </tbody></table></div><?php else: ?><p class="form-hint">No hay solicitudes para este filtro.</p><?php endif; ?>
    </section>

    <?php if ($selectedRequest): $currentAcademic = $selectedRequest['verificacion_actual']; $currentAcademicComplete = (bool) $selectedRequest['academic_verification_ready']; ?>
        <section class="card mg-panel">
            <h2>Solicitud #<?= (int) $selectedRequest['id_solicitud'] ?> · <?= e($selectedRequest['estado']) ?></h2>
            <div class="stat-grid"><article class="stat-card"><span class="stat-label">Estudiante / RU</span><strong><?= e($selectedRequest['estudiante']) ?><br><?= e($selectedRequest['registro_universitario'] ?? '—') ?></strong></article><article class="stat-card"><span class="stat-label">Carrera</span><strong><?= e($selectedRequest['nombre_carrera']) ?></strong></article><article class="stat-card"><span class="stat-label">Modalidad</span><strong><?= e($selectedRequest['modalidad']) ?></strong></article><article class="stat-card"><span class="stat-label">Cuenta</span><strong><?= e($selectedRequest['estado_usuario']) ?></strong></article></div>
            <p><strong>Tipo de trabajo:</strong> <?= e($selectedRequest['tipo_trabajo']) ?> · <strong>Enviada:</strong> <?= e($selectedRequest['enviado_en'] ?? '—') ?></p>
            <?php if ($selectedRequest['tema_preliminar']): ?><p><strong>Tema preliminar:</strong> <?= e($selectedRequest['tema_preliminar']) ?></p><?php endif; ?>
            <?php if ($selectedRequest['descripcion']): ?><p><strong>Descripción:</strong><br><?= nl2br(e($selectedRequest['descripcion'])) ?></p><?php endif; ?>
            <?php if ($selectedRequest['observaciones_estudiante']): ?><p><strong>Nota del estudiante:</strong><br><?= nl2br(e($selectedRequest['observaciones_estudiante'])) ?></p><?php endif; ?>
            <h3>Resumen académico registrado</h3>
            <p>Fuente: <strong><?= e($selectedRequest['fuente_verificacion_academica'] ?? ($selectedRequest['evidencia_academica'] ? 'Documento pendiente de revisión' : 'Pendiente')) ?></strong> · Plan #<?= e($selectedRequest['id_plan_verificado'] ?? '—') ?> · Materias aprobadas: <?= e($selectedRequest['materias_aprobadas_snapshot'] ?? '—') ?> / <?= e($selectedRequest['materias_requeridas_snapshot'] ?? '—') ?> · Promedio informativo: <?= $selectedRequest['promedio_snapshot'] === null ? '—' : e(number_format((float) $selectedRequest['promedio_snapshot'], 2)) ?> · Verificado: <?= e($selectedRequest['verificado_en'] ?? '—') ?></p>
            <h3>Estado académico actual</h3>
            <?php if ($currentAcademic): ?><p>Plan <?= e($currentAcademic['codigo_plan'] . ' / ' . $currentAcademic['version_plan']) ?> · Aprobadas <?= (int) $currentAcademic['materias_aprobadas'] ?> / <?= (int) $currentAcademic['materias_requeridas'] ?> · Promedio <?= $currentAcademic['promedio_aprobadas'] === null ? '—' : e(number_format((float) $currentAcademic['promedio_aprobadas'], 2)) ?></p>
                <?php if ($selectedRequest['materias_pendientes_actuales']): ?><ul><?php foreach ($selectedRequest['materias_pendientes_actuales'] as $subject): ?><li><?= e($subject['nombre_materia']) ?> — <?= $subject['registrada'] ? 'sin aprobación' : 'sin registro' ?></li><?php endforeach; ?></ul><?php endif; ?>
            <?php elseif ($selectedRequest['evidencia_academica']): ?><p class="alert">El historial oficial no está completo. Se usará el documento adjunto después de que Administración contraste las materias con el plan.</p>
            <?php else: ?><p class="alert">No existe un plan asignado con historial aprobado ni un documento de calificaciones para verificar.</p><?php endif; ?>
            <p><strong>Modalidad aún disponible:</strong> <?= (int) $selectedRequest['modalidad_disponible'] === 1 ? 'Sí' : 'No' ?></p>
        </section>

        <?php $evidence = $selectedRequest['evidencia_academica']; ?>
        <section class="card mg-panel">
            <h3>Evidencia de calificaciones</h3>
            <?php if ($evidence): ?>
                <p>Versión <?= (int)$evidence['numero_version'] ?> · Estado: <strong><?= e($evidence['estado']) ?></strong> · Plan <?= e($evidence['codigo_plan'] ? $evidence['codigo_plan'] . ' / ' . $evidence['version_plan'] : ($evidence['plan_referencia'] ?: 'Sin plan asignado; verificar malla manualmente')) ?> · Subida por <?= e($evidence['subido_por']) ?> el <?= e($evidence['subido_en']) ?></p>
                <p><a class="btn btn-sm btn-outline-primary" href="<?= e(app_url('modalidades-grado/solicitudes.php?id=' . $requestId . '&descargar_evidencia=' . (int)$evidence['id_evidencia'])) ?>">Abrir PDF privado</a></p>
                <?php if ($evidence['comentario_estudiante']): ?><p><strong>Comentario del estudiante:</strong> <?= nl2br(e($evidence['comentario_estudiante'])) ?></p><?php endif; ?>
                <?php if ($evidence['observacion_revision']): ?><p class="alert"><strong>Observación de revisión:</strong> <?= nl2br(e($evidence['observacion_revision'])) ?></p><?php endif; ?>
                <?php if ($evidence['materias_requeridas'] !== null): ?><p><strong>Resultado verificado:</strong> <?= (int)$evidence['materias_aprobadas'] ?> / <?= (int)$evidence['materias_requeridas'] ?> materias aprobadas · Promedio <?= e(number_format((float)$evidence['promedio_verificado'],2)) ?> · Revisor <?= e($evidence['revisado_por'] ?? '—') ?></p>
                    <?php if ($evidence['materias']): ?><div class="table-wrapper"><table><thead><tr><th>Materia obligatoria</th><th>Estado verificado</th><th>Nota</th><th>Periodo</th></tr></thead><tbody><?php foreach ($evidence['materias'] as $grade): ?><tr><td><?= e($grade['nombre_materia']) ?></td><td><?= e($grade['estado']) ?></td><td><?= e($grade['nota']) ?></td><td><?= e($grade['periodo'] ?? '—') ?></td></tr><?php endforeach; ?></tbody></table></div><?php endif; ?>
                <?php endif; ?>
            <?php else: ?><p>No hay un PDF adjunto. El estudiante debe cargar evidencia si el historial oficial no permite verificar el plan completo.</p><?php endif; ?>

            <?php if ($selectedRequest['estado'] === 'en_revision' && $evidence && $evidence['estado'] === 'pendiente'): ?>
                <h4>Revisar contra el plan asignado</h4>
                <p>Abra el PDF y registre el estado, nota y periodo de cada materia obligatoria. Graduación por Excelencia exige promedio mayor que 90. Verificar el documento no aprueba la solicitud; la decisión se toma por separado abajo.</p>
                <form method="post" action="<?= e(app_url('modalidades-grado/solicitudes.php?id=' . $requestId . '&estado=' . rawurlencode($state))) ?>">
                    <input type="hidden" name="csrf_token" value="<?= e(csrf_token()) ?>"><input type="hidden" name="id_solicitud" value="<?= $requestId ?>"><input type="hidden" name="id_evidencia" value="<?= (int)$evidence['id_evidencia'] ?>">
                    <?php if ($selectedRequest['materias_plan']): ?><div class="table-wrapper"><table><thead><tr><th>Materia obligatoria</th><th>Estado en certificado</th><th>Nota</th><th>Periodo</th></tr></thead><tbody>
                        <?php foreach ($selectedRequest['materias_plan'] as $subject): $subjectId=(int)$subject['id_materia']; ?>
                            <tr><td><?= e($subject['nombre_materia']) ?></td><td><select class="form-select" name="materias[<?= $subjectId ?>][estado]" required><option value="">Seleccione</option><option value="APROBADA">Aprobada</option><option value="REPROBADA">Reprobada</option></select></td><td><input class="form-control" type="number" min="0" max="100" step="0.01" name="materias[<?= $subjectId ?>][nota]" required></td><td><input class="form-control" maxlength="40" name="materias[<?= $subjectId ?>][periodo]" placeholder="Periodo" ></td></tr>
                        <?php endforeach; ?>
                    </tbody></table></div>
                    <?php else: ?>
                        <p class="alert">A este estudiante aún no se le asignó un plan digital. Contraste manualmente el certificado con la malla oficial de su carrera y registre <strong>todas</strong> las materias obligatorias. Cada línea: <code>Materia;APROBADA;nota;periodo</code>. Si falta alguna materia, observe el documento.</p>
                        <label>Plan/malla oficial contrastada<input class="form-control" name="plan_referencia" maxlength="100" placeholder="Código y versión del plan" required></label>
                        <label>Materias obligatorias verificadas<textarea class="form-control" name="materias_sin_plan" rows="10" placeholder="Matemática I;APROBADA;94;2025-1&#10;Base de Datos;APROBADA;92;2025-2" required></textarea></label>
                        <label class="mg-checkbox"><input type="checkbox" name="confirma_materias_plan" value="1"> Confirmo que contrasté el PDF con la malla oficial y anoté todas las materias obligatorias.</label>
                    <?php endif; ?>
                    <label>Observación de revisión (obligatoria si observa)<textarea class="form-control" name="observacion_revision" maxlength="5000" rows="2"></textarea></label>
                    <div class="mg-actions"><button class="btn btn-outline-primary" type="submit" name="accion" value="observar_evidencia" formnovalidate>Observar y devolver</button><button class="btn btn-primary" type="submit" name="accion" value="verificar_evidencia">Guardar verificación académica</button></div>
                </form>
            <?php elseif (!$evidence && $selectedRequest['estado'] === 'en_revision'): ?><p class="form-hint">El historial oficial no es suficiente y no hay documento que revisar; observe la solicitud o rechácela.</p><?php endif; ?>
        </section>

        <?php if ($selectedRequest['estado'] === 'enviada'): ?>
            <section class="card mg-panel"><h3>Iniciar revisión</h3><form method="post" action="<?= e(app_url('modalidades-grado/solicitudes.php?id=' . $requestId . '&estado=' . rawurlencode($state))) ?>"><input type="hidden" name="csrf_token" value="<?= e(csrf_token()) ?>"><input type="hidden" name="id_solicitud" value="<?= $requestId ?>"><label>Nota interna (opcional)<textarea class="form-control" name="observacion" rows="2" maxlength="5000"></textarea></label><button class="btn btn-primary" name="accion" value="iniciar_revision">Iniciar revisión</button></form></section>
        <?php elseif ($selectedRequest['estado'] === 'en_revision'): ?>
            <section class="card mg-panel"><h3>Decisión administrativa</h3><form class="mg-form-grid" method="post" action="<?= e(app_url('modalidades-grado/solicitudes.php?id=' . $requestId . '&estado=' . rawurlencode($state))) ?>"><input type="hidden" name="csrf_token" value="<?= e(csrf_token()) ?>"><input type="hidden" name="id_solicitud" value="<?= $requestId ?>"><label>Observación / motivo (obligatorio al observar o rechazar)<textarea class="form-control" name="observacion" rows="3" maxlength="5000"></textarea></label><div class="mg-actions"><button class="btn btn-outline-primary" name="accion" value="observar">Observar</button><button class="btn btn-outline-danger" name="accion" value="rechazar">Rechazar</button><button class="btn btn-primary" name="accion" value="aprobar" <?= !$currentAcademicComplete || (int) $selectedRequest['modalidad_disponible'] !== 1 || $selectedRequest['estado_usuario'] !== 'activo' ? 'disabled' : '' ?>>Aprobar solicitud</button></div></form></section>
        <?php elseif ($selectedRequest['estado'] === 'aprobada' && !$selectedRequest['id_habilitacion']): ?>
            <section class="card mg-panel"><h3>Habilitación formal</h3><p>La habilitación se registra aparte; no crea una inscripción formal.</p><form method="post" action="<?= e(app_url('modalidades-grado/solicitudes.php?id=' . $requestId . '&estado=' . rawurlencode($state))) ?>"><input type="hidden" name="csrf_token" value="<?= e(csrf_token()) ?>"><input type="hidden" name="id_solicitud" value="<?= $requestId ?>"><label>Observación (opcional)<textarea class="form-control" name="observacion" rows="2" maxlength="1000"></textarea></label><button class="btn btn-primary" name="accion" value="habilitar" <?= !$currentAcademicComplete || (int) $selectedRequest['modalidad_disponible'] !== 1 || $selectedRequest['estado_usuario'] !== 'activo' ? 'disabled' : '' ?>>Habilitar proceso</button></form></section>
        <?php elseif ($selectedRequest['id_habilitacion']): ?><section class="card mg-panel"><h3>Habilitación registrada</h3><p><?= e($selectedRequest['habilitado_en']) ?> por <?= e($selectedRequest['habilitado_por'] ?? 'Administración') ?><?= $selectedRequest['observacion_habilitacion'] ? ' — ' . e($selectedRequest['observacion_habilitacion']) : '' ?></p></section><?php endif; ?>

        <section class="card mg-panel"><h3>Historial de auditoría</h3><?php if ($selectedRequest['historial']): ?><div class="table-wrapper"><table><thead><tr><th>Fecha</th><th>Acción</th><th>Estado</th><th>Responsable</th><th>Comentario</th><th>Visibilidad</th><th>Resumen académico</th></tr></thead><tbody><?php foreach ($selectedRequest['historial'] as $event): ?><tr><td><?= e($event['ocurrido_en']) ?></td><td><?= e($event['accion']) ?></td><td><?= e(($event['estado_anterior'] ?? '—') . ' → ' . $event['estado_nuevo']) ?></td><td><?= e($event['actor']) ?></td><td><?= nl2br(e($event['comentario'] ?? '—')) ?></td><td><?= (int) $event['visible_estudiante'] === 1 ? 'Visible al estudiante' : 'Interno' ?></td><td><code><?= e($event['resumen_academico'] ?? '—') ?></code></td></tr><?php endforeach; ?></tbody></table></div><?php else: ?><p>Sin eventos.</p><?php endif; ?></section>
    <?php endif; ?>
</main>
<?php require __DIR__ . '/../layouts/footer.php'; ?>
